name: Deploy to SNUAAA AWS server

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install SSH Client
      run: sudo apt-get install -y sshpass

    - name: Sync files to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: archive.snuaaa.net
        SSH_USER: equipmentsystem
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        rsync -avz --no-times --no-perms -e "ssh -i private_key -o StrictHostKeyChecking=no" --exclude '.git/' ./EquipmentSystem/ $SSH_USER@$SSH_HOST:/var/www/vhosts/archive.snuaaa.net/EquipmentSystem

    - name: Set permissions
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: archive.snuaaa.net
        SSH_USER: equipmentsystem
      run: |
        ssh -i private_key -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "chmod 777 -R /var/www/vhosts/archive.snuaaa.net/EquipmentSystem"
